content_dir: 'content'
languages:
  - 'en'
  - 'zh'
  - 'ja'
title: 'zsai的博客'
desc: '记录与分享'
telegram_bot_token: '7562224843:AAEzzfcoLsygc-XFRATGLX5aOxTKWIacSAk'
telegram_channel_id: '@zsai010'
openai_api_key: 'sk-E2Fdl5s7EzepHPL8557602Ec8d404fEc80Db4d9a57CbBbC5'
openai_api_base: 'http://156.236.74.60:3100/v1'